version = 0.1

[default.deploy.parameters]
stack_name = "dataCountries"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\""
resolve_s3 = true
s3_prefix = "dataCountries"
image_repositories = []
